[package]
name = "rojo"
version = "0.6.0-dev"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
description = "Enables professional-grade development tools for Roblox developers"
license = "MPL-2.0"
repository = "https://github.com/rojo-rbx/rojo"
edition = "2018"

exclude = [
    "/plugin/**",
    "/test-projects/**",
]

[features]
default = []

# Enable this feature to live-reload assets from the web UI.
dev-live-assets = []

# Enables specifying user plugins in the project file. User plugins are Lua
# files and currently not fully implemented. See issue #55.
user-plugins = []

[workspace]
members = [
    "rojo-test",
    "rojo-insta-ext",
    "clibrojo",
]

default-members = [
    ".",
    "rojo-test",
    "rojo-insta-ext",
]

[lib]
name = "librojo"
path = "src/lib.rs"

[[bin]]
name = "rojo"
path = "src/bin.rs"

[[bench]]
name = "build"
harness = false

[dependencies]
clap = "2.27"
crossbeam-channel = "0.3.9"
csv = "1.0"
env_logger = "0.6"
failure = "0.1.3"
futures = "0.1"
globset = "0.4.4"
humantime = "1.3.0"
hyper = "0.12"
jod-thread = "0.1.0"
log = "0.4"
maplit = "1.0.1"
notify = "4.0"
rbx_binary = "0.4.1"
rbx_dom_weak = "1.9.0"
rbx_reflection = "3.1.388"
rbx_xml = "0.11.0"
regex = "1.0"
reqwest = "0.9.20"
ritz = "0.1.0"
rlua = "0.16.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
termcolor = "1.0.5"
uuid = { version = "0.7", features = ["v4", "serde"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.6.2"

[dev-dependencies]
rojo-insta-ext = { path = "rojo-insta-ext" }

lazy_static = "1.2"
paste = "0.1"
pretty_assertions = "0.6.1"
serde_yaml = "0.8.9"
tempfile = "3.0"
tokio = "0.1.22"
walkdir = "2.1"
criterion = "0.3"

[dev-dependencies.insta]
git = "https://github.com/mitsuhiko/insta"
features = ["redactions"]
