[package]
name = "rojo"
version = "0.5.0"
authors = ["Lucien Greathouse <me@lpghatguy.com>"]
description = "A tool to create robust Roblox projects"
license = "MIT"
repository = "https://github.com/LPGhatguy/rojo"

[lib]
name = "librojo"
path = "src/lib.rs"

[[bin]]
name = "rojo"
path = "src/bin.rs"

[dependencies]
clap = "2.27.1"
rouille = "2.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
notify = "4.0.0"
rand = "0.4"
regex = "1.0"
lazy_static = "1.0"

[dev-dependencies]
tempfile = "3"
