name: coverage

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: install-tarpaulin
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --force cargo-tarpaulin

    - name: Run cargo-tarpaulin
      uses: actions-rs/cargo@v1
      with:
        command: tarpaulin
        args: "-p capsule -l --count --exclude-files examples/* ffi/* macros/* rojo-test/* --out Lcov -Zpackage-features --features full"

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1.3.0
      with:
        artifact-name: code-coverage-report
        coverage-files: lcov.info
        minimum-coverage: 40
        github-token: ${{ secrets.GITHUB_TOKEN }}
