name: coverage

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: "0.16.0"
        args: "--exclude-files rojo-test/* -- --test-threads 1"
        out-type: "Lcov"


    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v1.3.0
      with:
        artifact-name: code-coverage-report
        coverage-files: lcov.info
        minimum-coverage: 40
        github-token: ${{ secrets.GITHUB_TOKEN }}
